version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - vaultwarden-data:/data/
    ports:
      - "80:80"
    env_file:
      - vaultwarden.env
volumes:
  vaultwarden-data:
    name: vaultwarden-data
